CREATE OR REPLACE TABLE MYDESK.PUBLIC.EDW_AUDIT_LOG (
    SOURCE_TABLE_NAME    VARCHAR(200),
    TARGET_TABLE_NAME    VARCHAR(200),
    SOURCE_RECORD_COUNT  NUMBER(10),
    TARGET_RECORD_COUNT  NUMBER(10),
    START_TIME           TIMESTAMP,
    END_TIME             TIMESTAMP,
    JOB_STATUS           VARCHAR(50),
    REASON_FOR_FAILURE   VARCHAR(1000)
);




-- 1. Base Staging Table
CREATE OR REPLACE TABLE MYDESK.PUBLIC.STAGE_CATALOG_PAGE (
    CP_CATALOG_PAGE_SK        NUMBER,
    CP_CATALOG_PAGE_ID        VARCHAR(16),
    CP_START_DATE_SK          NUMBER,
    CP_END_DATE_SK            NUMBER,
    CP_DEPARTMENT             VARCHAR(50),
    CP_CATALOG_NUMBER         NUMBER,
    CP_CATALOG_PAGE_NUMBER    NUMBER,
    CP_DESCRIPTION            VARCHAR(100),
    CP_TYPE                   VARCHAR(100)
);

-- 2. Derived Staging Table
CREATE OR REPLACE TABLE MYDESK.PUBLIC.STAGE_CATALOG_PAGE_DERIVED (
    INSERT_GMT_TIMESTAMP      TIMESTAMP,
    UPDATE_GMT_TIMESTAMP      TIMESTAMP,
    LOAD_DATE                 NUMBER,
    LOAD_IDENTIFIER           NUMBER,
    CP_CATALOG_PAGE_SK        NUMBER,
    CP_CATALOG_PAGE_ID        VARCHAR(16),
    CP_START_DATE_SK          NUMBER,
    CP_END_DATE_SK            NUMBER,
    CP_DEPARTMENT             VARCHAR(50),
    CP_CATALOG_NUMBER         NUMBER,
    CP_CATALOG_PAGE_NUMBER    NUMBER,
    CP_DESCRIPTION            VARCHAR(100),
    CP_TYPE                   VARCHAR(100)
);

-- 3. Final Dimension Table
CREATE OR REPLACE TABLE MYDESK.PUBLIC.DIM_CATALOG_PAGE (
    INSERT_GMT_TIMESTAMP      TIMESTAMP,
    UPDATE_GMT_TIMESTAMP      TIMESTAMP,
    LOAD_DATE                 NUMBER,
    LOAD_IDENTIFIER           NUMBER,
    CP_CATALOG_PAGE_SK        NUMBER,
    CP_CATALOG_PAGE_ID        VARCHAR(16),
    CP_START_DATE_SK          NUMBER,
    CP_END_DATE_SK            NUMBER,
    CP_DEPARTMENT             VARCHAR(50),
    CP_CATALOG_NUMBER         NUMBER,
    CP_CATALOG_PAGE_NUMBER    NUMBER,
    CP_DESCRIPTION            VARCHAR(100),
    CP_TYPE                   VARCHAR(100)
);




CREATE OR REPLACE PROCEDURE MYDESK.PUBLIC.DIM_CATALOG_PAGE_SP(TABLE_NAME VARCHAR(100))
RETURNS VARCHAR(100)
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
    V_START_TIME TIMESTAMP;
    V_END_TIME TIMESTAMP;
    V_SOURCE_TABLE_NAME VARCHAR(100);
    V_TARGET_TABLE_NAME VARCHAR(100);
    V_SOURCE_RECORD_COUNT NUMBER(10);
    V_TARGET_RECORD_COUNT NUMBER(10);
    V_STARTING_PROC TIMESTAMP;
    V_ENDING_PROC TIMESTAMP;
    V_ERROR_MESSAGE VARCHAR(1000);
    Q_STAGE_DELETE VARCHAR;
    Q_STAGE_INSERT VARCHAR;
    Q_DERIVED_DELETE VARCHAR;
    Q_DERIVED_INSERT VARCHAR;
    Q_DIM_DELETE VARCHAR;
    Q_DIM_INSERT VARCHAR;
BEGIN
    V_STARTING_PROC := CURRENT_TIMESTAMP();

    ---------------------------------------------------------------------------
    /* Step 1 */
    ---------------------------------------------------------------------------
    V_START_TIME := CURRENT_TIMESTAMP();
    Q_STAGE_DELETE := 'TRUNCATE TABLE MYDESK.PUBLIC.STAGE_' || :TABLE_NAME;
    V_SOURCE_TABLE_NAME := 'SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.' || :TABLE_NAME;
    V_TARGET_TABLE_NAME := 'MYDESK.PUBLIC.STAGE_' || :TABLE_NAME;

    SELECT COUNT(1) INTO :V_SOURCE_RECORD_COUNT FROM IDENTIFIER(:V_SOURCE_TABLE_NAME);
    EXECUTE IMMEDIATE Q_STAGE_DELETE;

    Q_STAGE_INSERT := 'INSERT INTO MYDESK.PUBLIC.STAGE_' || :TABLE_NAME || '
        SELECT 
            CP_CATALOG_PAGE_SK,
            CP_CATALOG_PAGE_ID,
            CP_START_DATE_SK,
            CP_END_DATE_SK,
            CP_DEPARTMENT,
            CP_CATALOG_NUMBER,
            CP_CATALOG_PAGE_NUMBER,
            CP_DESCRIPTION,
            CP_TYPE
        FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.' || :TABLE_NAME;
    EXECUTE IMMEDIATE Q_STAGE_INSERT;

    SELECT COUNT(1) INTO :V_TARGET_RECORD_COUNT FROM IDENTIFIER(:V_TARGET_TABLE_NAME);
    V_END_TIME := CURRENT_TIMESTAMP();

    INSERT INTO MYDESK.PUBLIC.EDW_AUDIT_LOG(
        SOURCE_TABLE_NAME, TARGET_TABLE_NAME, SOURCE_RECORD_COUNT, TARGET_RECORD_COUNT, START_TIME, END_TIME, JOB_STATUS, REASON_FOR_FAILURE
    ) VALUES (
        :V_SOURCE_TABLE_NAME, :V_TARGET_TABLE_NAME, :V_SOURCE_RECORD_COUNT, :V_TARGET_RECORD_COUNT, :V_START_TIME, :V_END_TIME, 'Success', NULL
    );

    ---------------------------------------------------------------------------
    /* Step 2 */
    ---------------------------------------------------------------------------
    V_START_TIME := CURRENT_TIMESTAMP();
    V_SOURCE_TABLE_NAME := 'MYDESK.PUBLIC.STAGE_' || :TABLE_NAME;
    V_TARGET_TABLE_NAME := 'MYDESK.PUBLIC.STAGE_' || :TABLE_NAME || '_DERIVED';

    SELECT COUNT(1) INTO :V_SOURCE_RECORD_COUNT FROM IDENTIFIER(:V_SOURCE_TABLE_NAME);
    Q_DERIVED_DELETE := 'TRUNCATE TABLE MYDESK.PUBLIC.STAGE_' || :TABLE_NAME || '_DERIVED';
    EXECUTE IMMEDIATE Q_DERIVED_DELETE;

    Q_DERIVED_INSERT := 'INSERT INTO MYDESK.PUBLIC.STAGE_' || :TABLE_NAME || '_DERIVED
        SELECT 
            CURRENT_TIMESTAMP() AS INSERT_GMT_TIMESTAMP,
            CURRENT_TIMESTAMP() AS UPDATE_GMT_TIMESTAMP,
            TO_NUMBER(TO_CHAR(CURRENT_DATE(), ''YYYYMMDD'')) AS LOAD_DATE,
            TO_NUMBER(TO_CHAR(CURRENT_DATE(), ''YYYYMMDDHH24MISS'')) AS LOAD_IDENTIFIER,
            CP_CATALOG_PAGE_SK,
            CP_CATALOG_PAGE_ID,
            CP_START_DATE_SK,
            CP_END_DATE_SK,
            CP_DEPARTMENT,
            CP_CATALOG_NUMBER,
            CP_CATALOG_PAGE_NUMBER,
            CP_DESCRIPTION,
            CP_TYPE
        FROM MYDESK.PUBLIC.STAGE_' || :TABLE_NAME;
    EXECUTE IMMEDIATE Q_DERIVED_INSERT;

    SELECT COUNT(1) INTO :V_TARGET_RECORD_COUNT FROM IDENTIFIER(:V_TARGET_TABLE_NAME);
    V_END_TIME := CURRENT_TIMESTAMP();

    INSERT INTO MYDESK.PUBLIC.EDW_AUDIT_LOG(
        SOURCE_TABLE_NAME, TARGET_TABLE_NAME, SOURCE_RECORD_COUNT, TARGET_RECORD_COUNT, START_TIME, END_TIME, JOB_STATUS, REASON_FOR_FAILURE
    ) VALUES (
        :V_SOURCE_TABLE_NAME, :V_TARGET_TABLE_NAME, :V_SOURCE_RECORD_COUNT, :V_TARGET_RECORD_COUNT, :V_START_TIME, :V_END_TIME, 'Success', NULL
    );

    ---------------------------------------------------------------------------
    /* Step 3 */
    ---------------------------------------------------------------------------
    V_START_TIME := CURRENT_TIMESTAMP();
    V_SOURCE_TABLE_NAME := 'MYDESK.PUBLIC.STAGE_' || :TABLE_NAME || '_DERIVED';
    V_TARGET_TABLE_NAME := 'MYDESK.PUBLIC.DIM_' || :TABLE_NAME;

    SELECT COUNT(1) INTO :V_SOURCE_RECORD_COUNT FROM IDENTIFIER(:V_SOURCE_TABLE_NAME);
    Q_DIM_DELETE := 'DELETE FROM MYDESK.PUBLIC.DIM_' || :TABLE_NAME || 
                    ' WHERE CP_CATALOG_PAGE_SK IN (SELECT DISTINCT CP_CATALOG_PAGE_SK FROM MYDESK.PUBLIC.STAGE_' || :TABLE_NAME || '_DERIVED)';
    EXECUTE IMMEDIATE Q_DIM_DELETE;

    Q_DIM_INSERT := 'INSERT INTO MYDESK.PUBLIC.DIM_' || :TABLE_NAME || '
        SELECT 
            INSERT_GMT_TIMESTAMP,
            UPDATE_GMT_TIMESTAMP,
            LOAD_DATE,
            LOAD_IDENTIFIER,
            CP_CATALOG_PAGE_SK,
            CP_CATALOG_PAGE_ID,
            CP_START_DATE_SK,
            CP_END_DATE_SK,
            CP_DEPARTMENT,
            CP_CATALOG_NUMBER,
            CP_CATALOG_PAGE_NUMBER,
            CP_DESCRIPTION,
            CP_TYPE
        FROM MYDESK.PUBLIC.STAGE_' || :TABLE_NAME || '_DERIVED';
    EXECUTE IMMEDIATE Q_DIM_INSERT;

    SELECT COUNT(1) INTO :V_TARGET_RECORD_COUNT FROM IDENTIFIER(:V_TARGET_TABLE_NAME);
    V_END_TIME := CURRENT_TIMESTAMP();

    INSERT INTO MYDESK.PUBLIC.EDW_AUDIT_LOG(
        SOURCE_TABLE_NAME, TARGET_TABLE_NAME, SOURCE_RECORD_COUNT, TARGET_RECORD_COUNT, START_TIME, END_TIME, JOB_STATUS, REASON_FOR_FAILURE
    ) VALUES (
        :V_SOURCE_TABLE_NAME, :V_TARGET_TABLE_NAME, :V_SOURCE_RECORD_COUNT, :V_TARGET_RECORD_COUNT, :V_START_TIME, :V_END_TIME, 'Success', NULL
    );

    V_ENDING_PROC := CURRENT_TIMESTAMP();
    RETURN 'Procedure successfully completed || Start Time : ' || :V_STARTING_PROC || ' || End Time : ' || :V_ENDING_PROC;

EXCEPTION
    WHEN OTHER THEN
        V_END_TIME := CURRENT_TIMESTAMP();
        V_ERROR_MESSAGE := SQLERRM;

        INSERT INTO MYDESK.PUBLIC.EDW_AUDIT_LOG(
            SOURCE_TABLE_NAME, TARGET_TABLE_NAME, SOURCE_RECORD_COUNT, TARGET_RECORD_COUNT, START_TIME, END_TIME, JOB_STATUS, REASON_FOR_FAILURE
        ) VALUES (
            :V_SOURCE_TABLE_NAME, :V_TARGET_TABLE_NAME, :V_SOURCE_RECORD_COUNT, :V_TARGET_RECORD_COUNT, :V_START_TIME, :V_END_TIME, 'FAILED', :V_ERROR_MESSAGE
        );
        RETURN 'Dim CatalogPage Procedure Failed: ' || :V_ERROR_MESSAGE;
END;

CALL MYDESK.PUBLIC.DIM_CATALOG_PAGE_SP('CATALOG_PAGE');


SELECT * FROM MYDESK.PUBLIC.EDW_AUDIT_LOG ORDER BY START_TIME DESC;

